from fastapi import APIRouter, Depends
from app.models.schemas import BookingRequest, BookingResponse
from app.db.database import get_db
from sqlalchemy.orm import Session

router = APIRouter()

@router.post("/", response_model=BookingResponse)
async def create_booking(booking: BookingRequest, db: Session = Depends(get_db)):
    # Implement logic to create a booking in the database
    # This is a placeholder implementation
    booking_id = 1  # In reality, this would be generated by the database
    return BookingResponse(id=booking_id, **booking.dict())